name: Azure OIDC Deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Azure login with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Get secret from Key Vault
      id: get-secret
      run: |
        REACT_APP_EXAMPLE=$(az keyvault secret show --vault-name "kvnaganreactjs1" --name "REACT-APP-EXAMPLE" --query value -o tsv)
        echo "::add-mask::$REACT_APP_EXAMPLE"
        echo "REACT_APP_EXAMPLE=$REACT_APP_EXAMPLE" >> $GITHUB_ENV
    
    - name: Get ACR access token
      id: get-acr-token
      run: |
        ACR_TOKEN=$(az acr login --name naganreactjsacr --expose-token --query accessToken -o tsv)
        echo "::add-mask::$ACR_TOKEN"
        echo "token=$ACR_TOKEN" >> $GITHUB_OUTPUT
    
    - name: Login to ACR with token
      uses: docker/login-action@v3
      with:
        registry: naganreactjsacr.azurecr.io
        username: 00000000-0000-0000-0000-000000000000
        password: ${{ steps.get-acr-token.outputs.token }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        build-args: |
          REACT_APP_EXAMPLE=${{ env.REACT_APP_EXAMPLE }}
        tags: |
          naganreactjsacr.azurecr.io/reactjs-sample:latest
          naganreactjsacr.azurecr.io/reactjs-sample:${{ github.sha }}
          naganreactjsacr.azurecr.io/reactjs-sample:${{ github.run_number }}

    - name: Deploy to Azure Container App
      run: |
        az containerapp update \
          --name reactjs-app \
          --resource-group rg-nagan-reactjs \
          --image naganreactjsacr.azurecr.io/reactjs-sample:${{ github.sha }}